--- #YAML:1.0
name:               Locale-Maketext-Utils
version:            0.13
abstract:           Adds some utility functionality and failure handling to Local::Maketext handles
author:
    - Daniel Muey, L<http://drmuey.com/cpan_contact.pl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    File::Slurp:          0
    Locale::Maketext:     0
    Locale::Maketext::Pseudo:  0
    Locales::Language:    0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
