# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext-Utils
version:      0.15
version_from: lib/Locale/Maketext/Utils.pm
installdirs:  site
requires:
    DateTime:                      0
    File::Slurp:                   0
    Locale::Maketext:              0
    Locales::Base:                 0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
