--- #YAML:1.0
name:               Locale-Maketext-Utils
version:            0.25
abstract:           Adds some utility functionality and failure handling to Local::Maketext handles
author:
    - Daniel Muey, L<http://drmuey.com/cpan_contact.pl>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0
    Encode:               0
    IO::Interactive::Tiny:  0
    Locale::Maketext:     1.22
    Locales:              0.26
    Module::Want:         0
    Net::LibIDN:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
