# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext-Utils
version:      v0.0.4
version_from: lib/Locale/Maketext/Utils.pm
installdirs:  site
requires:
    File::Slurp:                   0
    Locale::Maketext:              0
    Locales::Language:             0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
